const db = require('../config/connection');

exports.createTables = async(req, res) =>{
    
    db.query("CREATE TABLE IF NOT EXISTS `users` (   `user_id` int NOT NULL AUTO_INCREMENT,   `first_name` varchar(100) DEFAULT NULL,   `last_name` varchar(100) DEFAULT NULL,   `user_name` varchar(50) DEFAULT NULL,   `password_md5` varchar(50) DEFAULT NULL,   `phone_number` int DEFAULT NULL,   `address` text,   `city` varchar(50) DEFAULT NULL,   `district` varchar(50) DEFAULT NULL,   `email` varchar(200) DEFAULT NULL,   `role` enum('super_admin','admin','super_user','user','vendor') DEFAULT NULL,   `status` enum('active','inactive') DEFAULT NULL,   `create_date` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,   `created_by` int DEFAULT NULL,   `updated_date` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,   `updated_by` int DEFAULT NULL,   `department_id` int DEFAULT NULL,   `login_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,   PRIMARY KEY (`user_id`),   UNIQUE KEY `user_name` (`user_name`),   UNIQUE KEY `email` (`email`),   KEY `department_id` (`department_id`),   CONSTRAINT `users_ibfk_1` FOREIGN KEY (`department_id`) REFERENCES `departments` (`department_id`) ) ENGINE=InnoDB AUTO_INCREMENT=30 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;)")

    db.query("CREATE TABLE IF NOT EXISTS `departments` (   `department_id` int NOT NULL AUTO_INCREMENT,   `department_name` varchar(100) DEFAULT NULL,   `ranking` int DEFAULT NULL,   `status` enum('active','inactive') NOT NULL,   `created_date` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,   `created_by` int DEFAULT NULL,   `updated_date` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,   `updated_by` int DEFAULT NULL,   `department_code` varchar(10) DEFAULT NULL,   PRIMARY KEY (`department_id`) ) ENGINE=InnoDB AUTO_INCREMENT=14 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;)")

    db.query("CREATE TABLE IF NOT EXISTS `tendors` (   `id` int NOT NULL AUTO_INCREMENT,   `title` varchar(50) DEFAULT NULL,   `description` varchar(200) DEFAULT NULL,   `vendor_id` int DEFAULT NULL,   `work_id` varchar(50) DEFAULT NULL,   `location` varchar(150) DEFAULT NULL,   `status` enum('open','close','accept','reject') NOT NULL,   `json_status` varchar(200) DEFAULT NULL,   `tender_cost` int DEFAULT NULL,   `start_date` datetime DEFAULT NULL,   `end_date` datetime DEFAULT NULL,   `file` varchar(50) DEFAULT NULL,   `department_id` int DEFAULT NULL,   `created_date` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,   `created_by` int DEFAULT NULL,   `updated_date` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,   `updated_by` int DEFAULT NULL,   PRIMARY KEY (`id`),   KEY `department_id` (`department_id`),   CONSTRAINT `tendors_ibfk_2` FOREIGN KEY (`department_id`) REFERENCES `departments` (`department_id`) ) ENGINE=InnoDB AUTO_INCREMENT=15 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;)")

    db.query("CREATE TABLE IF NOT EXISTS `survey_report` (   `id` int NOT NULL AUTO_INCREMENT,   `title` varchar(50) DEFAULT NULL,   `description` varchar(200) DEFAULT NULL,   `vendor_id` int DEFAULT NULL,   `work_id` varchar(50) DEFAULT NULL,   `location` varchar(150) DEFAULT NULL,   `status` enum('open','close','accept','reject') NOT NULL,   `json_status` varchar(200) DEFAULT NULL,   `survey_cost` int DEFAULT NULL,   `start_date` datetime DEFAULT NULL,   `end_date` datetime DEFAULT NULL,   `file` varchar(50) DEFAULT NULL,   `department_id` int DEFAULT NULL,   `created_date` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,   `created_by` int DEFAULT NULL,   `updated_date` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,   `updated_by` int DEFAULT NULL,   PRIMARY KEY (`id`) ) ENGINE=InnoDB AUTO_INCREMENT=15 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;)")

    db.query("CREATE TABLE IF NOT EXISTS `work_orders` (   `id` int NOT NULL AUTO_INCREMENT,   `title` varchar(50) DEFAULT NULL,   `description` varchar(200) DEFAULT NULL,   `vendor_id` int DEFAULT NULL,   `work_id` varchar(50) DEFAULT NULL,   `location` varchar(150) DEFAULT NULL,   `status` enum('open','close','accept','reject') NOT NULL,   `json_status` varchar(200) DEFAULT NULL,   `work_cost` int DEFAULT NULL,   `start_date` datetime DEFAULT NULL,   `end_date` datetime DEFAULT NULL,   `file` varchar(50) DEFAULT NULL,   `department_id` int DEFAULT NULL,   `created_date` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,   `created_by` int DEFAULT NULL,   `updated_date` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,   `updated_by` int DEFAULT NULL,   PRIMARY KEY (`id`) ) ENGINE=InnoDB AUTO_INCREMENT=15 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;)")

    db.query("CREATE TABLE IF NOT EXISTS `works` (   `work_id` int NOT NULL AUTO_INCREMENT,   `work_name` varchar(100) NOT NULL,   `created_date` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,   `created_by` int DEFAULT NULL,   `updated_date` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,   `updated_by` int DEFAULT NULL,   `temp1` int DEFAULT NULL,   `temp2` int DEFAULT NULL,   PRIMARY KEY (`work_id`) ) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;)")

    db.query("CREATE TABLE IF NOT EXISTS `vendors` (   `vendor_id` int NOT NULL AUTO_INCREMENT,   `vendor_name` varchar(100) DEFAULT NULL,   `phone_number` int DEFAULT NULL,   `email` varchar(100) DEFAULT NULL,   `user_name` varchar(50) DEFAULT NULL,   `password_md5` varchar(50) DEFAULT NULL,   `address` varchar(200) DEFAULT NULL,   `city` varchar(50) DEFAULT NULL,   `state` varchar(50) DEFAULT NULL,   `gst_num` int DEFAULT NULL,   `status` enum('active','inactive') DEFAULT NULL,   `created_date` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,   `created_by` int DEFAULT NULL,   `updated_date` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,   `updated_by` int DEFAULT NULL,   PRIMARY KEY (`vendor_id`),   UNIQUE KEY `email` (`email`,`user_name`) ) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;)")

    db.query("CREATE TABLE IF NOT EXISTS `transactions` (   `id` int NOT NULL AUTO_INCREMENT,   `trsxcn_from` varchar(50) DEFAULT NULL,   `trsxcn_to` varchar(50) DEFAULT NULL,   `category` varchar(100) DEFAULT NULL,   `title` varchar(100) DEFAULT NULL,   `remarks` varchar(200) DEFAULT NULL,   `mode` varchar(50) DEFAULT NULL,   `trscxn_date` datetime DEFAULT NULL,   `amount` decimal(10,0) DEFAULT NULL,   `created_date` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,   `created_by` int DEFAULT NULL,   `updated_date` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,   `updated_by` int DEFAULT NULL,   PRIMARY KEY (`id`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;)")

    db.query("CREATE TABLE IF NOT EXISTS `invoices` (   `invoice_id` int NOT NULL AUTO_INCREMENT,   `vendor_id` int DEFAULT NULL,   `tendor_id` int DEFAULT NULL,   `title` varchar(50) DEFAULT NULL,   `remarks` varchar(200) DEFAULT NULL,   `attachments` varchar(200) DEFAULT NULL,   `inventory_details` json DEFAULT NULL,   `status` enum('open','cancel','paid') NOT NULL,   `amount` int DEFAULT NULL,   `tax` int DEFAULT NULL,   `grand_total` int DEFAULT NULL,   `created_date` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,   `created_by` int DEFAULT NULL,   `updated_date` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,   `updated_by` int DEFAULT NULL,   `invoice_details_id` int DEFAULT NULL,   PRIMARY KEY (`invoice_id`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;)")

    db.query("CREATE TABLE IF NOT EXISTS `invoices_audit_log` (   `invoices_audit_log_id` int NOT NULL AUTO_INCREMENT,   `vendor_id` int DEFAULT NULL,   `tendor_id` int DEFAULT NULL,   `title` varchar(50) DEFAULT NULL,   `remarks` varchar(200) DEFAULT NULL,   `attachments` varchar(200) DEFAULT NULL,   `inventory_details` json DEFAULT NULL,   `status` enum('open','cancel','paid') NOT NULL,   `amount` int DEFAULT NULL,   `tax` int DEFAULT NULL,   `grand_total` int DEFAULT NULL,   `created_date` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,   `created_by` int DEFAULT NULL,   `updated_date` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,   `updated_by` int DEFAULT NULL,   `invoices_id` int DEFAULT NULL,   `updated_details` json DEFAULT NULL,   `method` enum('update','delete') DEFAULT NULL,   PRIMARY KEY (`invoices_audit_log_id`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;)")

    db.query("CREATE TABLE IF NOT EXISTS `inventory` (   `item_id` int NOT NULL AUTO_INCREMENT,   `item_name` varchar(50) DEFAULT NULL,   `quantity` int DEFAULT NULL,   `price` int DEFAULT NULL,   `tax` int DEFAULT NULL,   `created_date` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,   `created_by` int DEFAULT NULL,   `updated_date` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,   `updated_by` int DEFAULT NULL,   PRIMARY KEY (`item_id`) ) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;)")

    db.query("CREATE TABLE IF NOT EXISTS `funds` (   `fund_id` int NOT NULL AUTO_INCREMENT,   `fund_type` varchar(100) DEFAULT NULL,   `fund_description` varchar(200) DEFAULT NULL,   `transaction_mode` enum('interent_banking','cheque','cash','card','upi') DEFAULT NULL,   `fund_value` int DEFAULT NULL,   `fund_released_date` datetime DEFAULT NULL,   `created_date` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,   `created_by` int DEFAULT NULL,   `updated_date` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,   `updated_by` int DEFAULT NULL,   PRIMARY KEY (`fund_id`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;)")

    db.query("CREATE TABLE IF NOT EXISTS `account_details` (   `id` int NOT NULL AUTO_INCREMENT,   `internet_banking` decimal(10,0) DEFAULT NULL,   `cash` decimal(10,0) DEFAULT NULL,   `cheque` decimal(10,0) DEFAULT NULL,   `card` decimal(10,0) DEFAULT NULL,   `upi` decimal(10,0) DEFAULT NULL,   `total` decimal(10,0) DEFAULT NULL,   `created_date` datetime NOT NULL,   `created_by` int DEFAULT NULL,   `updated_date` datetime NOT NULL,   `updated_by` int DEFAULT NULL,   PRIMARY KEY (`id`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;)")
}